version: '3.5'
services:

  ldap:
    image: osixia/openldap:${OPENLDAP_VERSION}
    hostname: ldap
    container_name: ldap
    ports:
      - "389:389"
    environment:
        LDAP_ORGANISATION: "MyCompany"
        LDAP_DOMAIN: "mycompany.com"
        LDAP_BASE_DN: "dc=mycompany,dc=com"
        LDAP_ADMIN_PASSWORD: "admin-secret"
        LDAP_CONFIG_PASSWORD: "config-secret"
        LDAP_READONLY_USER: "true"
        LDAP_READONLY_USER_USERNAME: "mds"
        LDAP_READONLY_USER_PASSWORD: "mds-secret"
        #LDAP_TLS_VERIFY_CLIENT: try
        #LDAP_TLS_CRT_FILENAME: ldap.kafka-network_cert.pem
        #LDAP_TLS_KEY_FILENAME: ldap.kafka-network_key.pem
        #LDAP_TLS_CA_CRT_FILENAME: ca.crt
        #LDAP_TLS: 'true'
    volumes:
      - ./volumes/ldap/data:/var/lib/ldap
      - ./volumes/ldap/config:/etc/ldap/slapd.d
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ./certs:/container/service/slapd/assets/certs:ro
    command: "--copy-service --loglevel debug"
    networks:
      - kafka_network

networks:
  kafka_network:
    name: kafka-network
